import React,{useState} from "react";
import {useData} from "../hooks/useData";
import {api,message} from "../api/client";
import {Field,today} from "../components/UI";
export default function WeeklyOffs(){
 const [month,setMonth]=useState(today().slice(0,7)),[edit,setEdit]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const vehicles=useData("/masters/vehicles"),customers=useData("/masters/customers"),offs=useData("/masters/weeklyOffs?month="+month);
 const rowsFor=(vehicleId,customerId)=> (offs.data||[]).filter(r=>r.vehicleId===vehicleId&&r.customerId===customerId);
 function open(vehicleId="",customerId="") {setError("");const rows=rowsFor(vehicleId,customerId);setEdit({vehicleId,customerId,dates:rows.map(r=>String(r.date).slice(0,10)).sort(),expectedRows:rows.map(r=>({_id:r._id,updatedAt:r.updatedAt}))});}
 function select(key,value){const next={...edit,[key]:value},rows=rowsFor(next.vehicleId,next.customerId);setEdit({...next,dates:rows.map(r=>String(r.date).slice(0,10)).sort(),expectedRows:rows.map(r=>({_id:r._id,updatedAt:r.updatedAt}))});}
 async function save(e){e.preventDefault();setBusy(true);setError("");try{await api.put("/masters/weeklyOffs/month",{...edit,month});offs.reload();setEdit(null);setSuccess("Weekly off dates saved");}catch(e){setError(message(e));}finally{setBusy(false);}}
 const groups=new Map();for(const r of offs.data||[]){const key=r.vehicleId+":"+r.customerId;if(!groups.has(key))groups.set(key,{vehicleId:r.vehicleId,customerId:r.customerId,dates:[]});groups.get(key).dates.push(String(r.date).slice(0,10));}
 return <><div className="page-head"><h1>Vehicle weekly offs</h1><button disabled={!!offs.loading} onClick={()=>open()}>+ Add</button></div><p>Choose a vehicle once and add all its off dates for the month in one modal. Without logged dates, billing uses one weekly off per seven days.</p><Field name="month" label="Month" type="month" value={month} onChange={(_,v)=>setMonth(v)}/>{success&&<p className="success">{success}</p>}{!edit&&error&&<p className="error">{error}</p>}{offs.error&&<p className="error">{message(offs.error)}</p>}
 <div className="card-grid">{Array.from(groups.values()).map(g=><button className="record card" key={g.vehicleId+g.customerId} onClick={()=>open(g.vehicleId,g.customerId)}><h3>{vehicles.data?.find(v=>v._id===g.vehicleId)?.vehicleNumber||"Vehicle unavailable"}</h3><p>{customers.data?.find(c=>c._id===g.customerId)?.companyName||"Customer unavailable"}</p><p>{g.dates.sort().join(", ")}</p><strong>{g.dates.length} off days</strong></button>)}</div>{!groups.size&&!offs.loading&&<p className="state">No weekly offs logged for this month.</p>}
 {edit&&<div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="page-head"><h2>Vehicle weekly offs - {month}</h2><button className="quiet" type="button" disabled={busy} onClick={()=>setEdit(null)}>Close</button></div><div className="form-grid"><Field name="customerId" label="Billing customer" required options={(customers.data||[]).map(c=>({value:c._id,label:c.companyName}))} value={edit.customerId} onChange={select}/><Field name="vehicleId" label="Branded vehicle" required options={(vehicles.data||[]).filter(v=>v.branded).map(v=>({value:v._id,label:v.vehicleNumber}))} value={edit.vehicleId} onChange={select}/></div>
 <div style={{maxHeight:340,overflowY:"auto"}}>{edit.dates.map((date,index)=><div className="actions" key={index}><Field name="date" label={"Off day "+(index+1)} type="date" required value={date} onChange={(_,value)=>setEdit({...edit,dates:edit.dates.map((d,i)=>i===index?value:d)})}/><button type="button" className="quiet" disabled={busy} onClick={()=>setEdit({...edit,dates:edit.dates.filter((_,i)=>i!==index)})}>Remove day</button></div>)}</div>
 <button type="button" className="quiet" disabled={busy} onClick={()=>setEdit({...edit,dates:[...edit.dates,month+"-01"]})}>+ Add another day</button><p>{edit.dates.length} off days. Saving zero dates restores the default weekly-off allowance.</p>{error&&<p className="error">{error}</p>}<button className="wide" disabled={busy||offs.loading||!edit.vehicleId||!edit.customerId}>{busy?"Saving...":"Save all off days"}</button></form></div>}
 </>;
}
