import React,{useState} from "react";
import {useNavigate} from "react-router-dom";
import {useData} from "../hooks/useData";
import {api,message} from "../api/client";
import {Field,Calculation,today} from "../components/UI";
import {sites} from "../../../shared/sites.js";
export default function AdhocTripForm({existing,onClose}){
 const nav=useNavigate(),vehicles=useData("/masters/vehicles"),customers=useData("/masters/customers");
 const [v,setV]=useState(existing?{...existing,customerId:existing.customerId?._id||existing.customerId,vehicleId:existing.vehicleId?._id||existing.vehicleId,periodFrom:String(existing.periodFrom).slice(0,10),periodTo:String(existing.periodTo).slice(0,10),entries:existing.entries.map(e=>({...e,date:String(e.date).slice(0,10)}))}:{site:"Inbound",adhocService:"City",dutyKind:"Adhoc",customerId:"",vehicleId:"",periodFrom:today(),periodTo:today(),distanceBand:"0-50",distanceKm:0,nightDetention:false,pickupLocation:"Cargo",dropLocation:"MIDC",entries:[{date:today(),openingTime:"07:00",closingTime:"15:00",perTripHours:8}]}),[preview,setPreview]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const change=(k,val)=>{setPreview(null);setV(x=>{if(k==="site"){const s=sites.find(s=>s.value===val);return {...x,site:val,adhocService:["Inbound","Outbound"].includes(val)?"City":"Kilometre",pickupLocation:s.origin,dropLocation:s.destination,nightDetention:false,entries:[{...x.entries[0],chaName:val==="Inbound"?x.entries[0].chaName:"",huNumber:val==="Inbound"?"":x.entries[0].huNumber,mrbArrivalTime:val==="Inbound"?x.entries[0].mrbArrivalTime:""}]};}if(k==="periodFrom")return {...x,periodFrom:val,periodTo:val,entries:[{...x.entries[0],date:val,closingDate:""}]};return {...x,[k]:val};});};
 const entryChange=(k,val)=>change("entries",[{...v.entries[0],[k]:val}]);
 async function review(e){e.preventDefault();setBusy(true);setError("");try{setPreview((await api.post("/trips/preview",v)).data.data);}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function save(status){setBusy(true);try{const payload={...v,status,expectedTotal:preview.calculation.totalAmount};const r=await api[existing?"patch":"post"]("/trips"+(existing?"/"+existing._id:""),payload);onClose?.();nav("/trips/"+r.data.data._id);}catch(e){setError(message(e));}finally{setBusy(false);}}
 const city=v.adhocService==="City",entry=v.entries[0];
 return <section><div className="page-head"><h1>{existing?"Edit":"Add"} Adhoc trip</h1>{onClose&&<button className="quiet" onClick={onClose}>Close</button>}</div>{error&&<p className="error">{error}</p>}<form onSubmit={review}><div className="card form-grid"><Field name="customerId" label="Billing customer" required options={customers.data?.map(c=>({value:c._id,label:c.companyName}))} value={v.customerId} onChange={change}/><Field name="site" label="Site" required options={sites} value={v.site} onChange={change}/><Field name="vehicleId" label="Adhoc vehicle" required options={vehicles.data?.filter(v=>!v.branded).map(v=>({value:v._id,label:v.vehicleNumber+" / "+v.vehicleType}))} value={v.vehicleId} onChange={change}/><Field name="periodFrom" label="Date" type="date" required value={v.periodFrom} onChange={change}/>{v.site==="Inbound"?<><Field name="chaName" label="CHA name" value={entry.chaName} onChange={entryChange}/><Field name="mrbArrivalTime" label="MIDC arrival time" type="time" value={entry.mrbArrivalTime} onChange={entryChange}/></>:<Field name="huNumber" label="HUID number" value={entry.huNumber} onChange={entryChange}/>}{!city&&<><Field name="distanceBand" label="Kilometre service" required options={["0-50","50-150","Above 150"]} value={v.distanceBand} onChange={change}/><Field name="distanceKm" label="Actual KM (required above 150)" type="number" required={v.distanceBand==="Above 150"} value={v.distanceKm} onChange={change}/><Field name="pickupLocation" label="Origin" value={v.pickupLocation} onChange={change}/><Field name="dropLocation" label="Destination" value={v.dropLocation} onChange={change}/></>}{[["openingTime","Opening time","time"],["closingTime","Closing time","time"],["closingDate","Closing date (optional for multi-day duty)","date"]].map(([k,label,type])=><Field key={k} name={k} label={label} type={type} required={k!=="closingDate"} value={entry[k]} onChange={entryChange}/>)}{city&&<Field name="nightDetention" label="Apply night detention" type="checkbox" value={v.nightDetention} onChange={change}/>}<p>One trip includes 8 hours. OT uses exact minutes. PNQ above 150 KM includes 16 hours for detention. Monthly parking is added once in the Excel summary.</p></div><button disabled={busy}>Calculate & review</button></form>{preview&&<><Calculation value={preview} site={v.site} distanceBand={v.distanceBand} compact/><div className="actions"><button disabled={busy} className="quiet" onClick={()=>save("Draft")}>Save draft</button><button disabled={busy} onClick={()=>save("Submitted")}>Save trip</button></div></>}</section>;
}
