import React,{useState} from "react";
import {api,download,message} from "../api/client";
export default function BrandedImport({customers,onImported}){
 const [open,setOpen]=useState(false),[customer,setCustomer]=useState(""),[file,setFile]=useState(null),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function upload(confirm=false){setBusy(true);setError("");try{const form=new FormData();form.append("file",file);form.append("customerId",customer);if(confirm)form.append("confirm","true");const result=(await api.post("/imports/branded-logs",form)).data.data;if(confirm){onImported(result.count);setOpen(false);setPreview(null);setFile(null);}else setPreview(result);}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <><button className="quiet" onClick={()=>{setOpen(true);setError("");}}>Import Excel</button><button className="quiet" onClick={async()=>{try{await download("/exports/branded-log-template.xlsx","branded-log-template.xlsx");}catch(e){setError(message(e));setOpen(true);}}}>Download import template</button>
 {open && <div className="modal-backdrop"><section className="modal card"><div className="page-head"><h2>Import branded shift logs</h2><button className="quiet" disabled={busy} onClick={()=>setOpen(false)}>Close</button></div>
 <p>Use the template or exported branded log. KM, hours and ADC are calculated automatically. Each row must be an 8-hour shift. Enter loading / hold location text in the odometer cells for a held row.</p>
 <label className="field">Billing customer<select value={customer} onChange={e=>{setCustomer(e.target.value);setPreview(null);}}><option value="">Select customer</option>{customers.map(c=><option key={c._id} value={c._id}>{c.companyName}</option>)}</select></label>
 <label className="field">Excel workbook<input type="file" accept=".xlsx,.xls" onChange={e=>{setFile(e.target.files[0]||null);setPreview(null);}}/></label>
 {error && <p className="error">{error}</p>}<button disabled={busy||!customer||!file} onClick={()=>upload(false)}>{busy?"Checking...":"Preview import"}</button>
 {preview && <><p>{preview.rows.length} parsed shifts; {preview.errors.length} row errors. Nothing is saved until confirmed.</p>{preview.errors.map((e,k)=><p className="error" key={k}>{e.sheet}, row {e.row}: {e.message}</p>)}<div className="sheet-scroll" style={{maxHeight:300,overflowY:"auto"}}><table className="trip-sheet"><thead><tr><th>Row</th><th>Date</th><th>Vehicle</th><th>KM</th><th>Opening</th><th>Closing</th><th>Hours</th><th>Airport fee</th></tr></thead><tbody>{preview.rows.slice(0,50).map((r,k)=><tr key={k}><td>{r.row}</td><td>{r.date}</td><td>{r.vehicleNumber}</td><td>{r.distanceKm}</td><td>{r.openingTime}</td><td>{r.closingTime}</td><td>{r.totalHours}</td><td>{r.airportFee}</td></tr>)}</tbody></table></div><button disabled={busy||!preview.rows.length||preview.errors.length>0} onClick={()=>upload(true)}>Confirm import ({preview.rows.length} shifts)</button></>}
 </section></div>}</>;
}
