import { sites } from "../../../shared/sites.js";
const f = (name, label, type = "text", options) => ({
  name,
  label,
  type,
  options,
});
const status = (options) => f("status", "Status", "text", options);
const notes = f("notes", "Notes", "textarea");
export const config = {
  agreements: {
    title:"Vehicle agreements", label:"name", id:"agreementId",
    defaults:{shiftHours:8,fixedKm:3000,fixedRate:0,mileage:1,fuelType:"Diesel",fuelRate:0,amcRate:0,serviceRate:0,overtimeRate:0,managementMonthly:0,parkingMonthly:0,airportEntryRate:0,airportTaxable:false,contractYear:1,active:true},
    fields:[f("name","Agreement name"),f("vehicleId","Vehicle"),f("customerId","Billing customer"),f("site","Site","text",sites),
      f("effectiveFrom","Effective from","date"),f("effectiveTo","Effective to","date"),f("deploymentDate","Deployment date","date"),
      f("contractYear","Vehicle contract year","number"),f("shiftHours","Shift hours","text",["8","16","24"]),
      f("fixedKm","Contracted monthly KM","number"),f("fixedRate","Fixed rate per KM","number"),f("mileage","Agreed mileage (KM per fuel unit)","number"),
      f("fuelType","Fuel type","text",["Diesel","CNG","Petrol"]),f("fuelRate","Default fuel rate","number"),
      f("amcRate","AMC per actual KM","number"),f("serviceRate","Additional service per shift","number"),f("overtimeRate","Additional duty per hour","number"),
      f("managementMonthly","Monthly management charge for this vehicle","number"),f("parkingMonthly","Monthly parking for this vehicle","number"),
      f("airportEntryRate","Airport entry per token","number"),f("airportTaxable","Airport entry taxable","checkbox"),f("active","Active","checkbox"),notes],
  },
  vehicles: {
    title: "Vehicles",
    label: "vehicleNumber",
    id: "vehicleId",
    defaults: { vehicleType: "17 FT", status: "Active" },
    fields: [
      f("vehicleNumber", "Vehicle number"),
      f("vehicleType", "Vehicle type", "text", [
        "8 FT",
        "9 FT",
        "14 FT",
        "17 FT",
        "20 FT",
        "Custom",
      ]),
      f("customVehicleType", "Custom type"),
      f("capacity", "Capacity"),
      status(["Active", "Maintenance", "Inactive"]),
      notes,
    ],
  },
  drivers: {
    title: "Drivers",
    label: "fullName",
    id: "driverId",
    defaults: { status: "Active" },
    fields: [
      f("fullName", "Full name"),
      f("phone", "Phone", "tel"),
      f("licenseNumber", "Licence number"),
      f("licenseExpiry", "Licence expiry", "date"),
      f("age", "Age", "number"),
      f("experienceYears", "Experience years", "number"),
      f("address", "Address", "textarea"),
      f("assignedVehicleId", "Assigned vehicle"),
      status(["Active", "On Leave", "Inactive"]),
      notes,
    ],
  },
  customers: {
    title: "Customers",
    label: "companyName",
    id: "customerId",
    defaults: {
      stateCode: "27",
      state: "Maharashtra",
      creditDays: 30,
      openingBalance: 0,
      active: true,
    },
    fields: [
      f("companyName", "Company name"),
      f("contactPerson", "Contact person"),
      f("phone", "Phone", "tel"),
      f("email", "Email", "email"),
      f("address", "Address", "textarea"),
      f("city", "City"),
      f("state", "State"),
      f("stateCode", "State code"),
      f("gstin", "GSTIN"),
      f("dhlGstin", "DHL GSTIN"),
      f("creditDays", "Credit days", "number"),
      f("openingBalance", "Opening balance", "number"),
      f("active", "Active", "checkbox"),
      notes,
    ],
  },
  routes: {
    title: "Routes & locations",
    label: "routeName",
    id: "routeId",
    defaults: { category: "Regular", active: true, order: 0 },
    fields: [
      f("routeName", "Route name"),
      f("pickupLocation", "Pickup"),
      f("dropLocation", "Drop"),
      f("category", "Category", "text", [
        "Inbound",
        "Outbound",
        "Regular",
        "Special",
      ]),
      f("order", "Display order", "number"),
      f("active", "Active", "checkbox"),
      notes,
    ],
  },
  rates: {
    title: "Rate chart",
    label: "vehicleType",
    id: "rateId",
    defaults: {
      minKm: 0,
      maxKm: 50,
      baseHours: 8,
      baseRate: 0,
      perKmRate: 0,
      perHourRate: 0,
      overtimeRate: 0,
      billingMethod: "Fixed + Overtime",
      effectiveFrom: "2026-01-01",
      active: true,
      minExclusive: false,
    },
    fields: [
      f("routeId", "Route"),
      f("vehicleType", "Vehicle type", "text", [
        "8 FT",
        "9 FT",
        "14 FT",
        "17 FT",
        "20 FT",
        "Custom",
      ]),
      f("minKm", "Minimum KM", "number"),
      f("maxKm", "Maximum KM (blank = unlimited)", "number"),
      f("minExclusive", "Exclude minimum boundary", "checkbox"),
      f("baseHours", "Included duty hours", "number"),
      f("baseRate", "Base rate", "number"),
      f("perKmRate", "Per KM rate", "number"),
      f("perHourRate", "Per hour rate", "number"),
      f("overtimeRate", "Overtime per hour", "number"),
      f("billingMethod", "Billing method", "text", [
        "Fixed Trip Rate",
        "Per KM",
        "Per Hour",
        "Fixed + Overtime",
        "Mutually Agreed / Manual",
      ]),
      f("effectiveFrom", "Effective from", "date"),
      f("effectiveTo", "Effective to", "date"),
      f("active", "Active", "checkbox"),
      notes,
    ],
  },
  users: {
    title: "User management",
    label: "name",
    id: "username",
    defaults: { active: true, role: "MANAGER" },
    fields: [
      f("name", "Name"),
      f("username", "Username"),
      f("password", "Password (blank preserves current)", "password"),
      f("role", "Role", "text", ["ADMIN", "MANAGER", "DRIVER"]),
      f("driverId", "Driver record"),
      f("active", "Active", "checkbox"),
    ],
  },
};
