import {durationText} from "./sites.js";
export const cityColumns=[["SR.NO","srNo"],["DATE","date"],["VEHICLE NO","vehicleNo"],["CHA NAME","chaName"],["VEHICLE TYPE","vehicleType"],["OPENING TIME","openingTime"],["MIDC ARRIVAL TIME","mrbArrivalTime"],["CLOSING TIME","closingTime"],["PER TRIP HRS","perTripHours"],["TOTAL HRS","totalHours"],["O.T IN HRS","gtInHours"],["8 HRS PER TRIP CHARGES","tripCharges"]];
export const kmColumns=[["SR.NO","srNo"],["DATE","date"],["VEHICLE - NO","vehicleNo"],["VEHICLE TYPE","vehicleType"],["HUID NO","huNumber"],["ORIGIN","pickupLocation"],["DESTINATION","dropLocation"],["OPENING TIME","openingTime"],["CLOSING TIME","closingTime"],["PER TRIP HRS","perTripHours"],["TOTAL HRS","totalHours"],["O.T IN HRS","gtInHours"],["TRIP CHARGES","tripCharges"],["TOLL AND PARKING","tollParking"],["TOTAL SDC CHARGES","totalServiceCharges"]];
export const isCity=site=>["Inbound","Outbound"].includes(site);
export function adhocRows(trips,passes=[]){
 const sorted=[...trips].sort((a,b)=>new Date(a.periodFrom)-new Date(b.periodFrom)||String(a.entries?.[0]?.openingTime||"").localeCompare(String(b.entries?.[0]?.openingTime||""))||String(a._id).localeCompare(String(b._id))),seen=new Set();
 return sorted.map((t,index)=>{const e=t.entries?.[0]||{},key=t.vehicleNumber+":"+new Date(t.periodFrom).toISOString().slice(0,7),parking=isCity(t.site)||seen.has(key)?0:Number(t.parkingSnapshot||0);seen.add(key);const customer=String(t.customerId?._id||t.customerId||""),month=new Date(t.periodFrom).toISOString().slice(0,7),passKey=customer+":"+t.site+":"+month,pass=passes.find(p=>!p.archived&&String(p.customerId?._id||p.customerId)===customer&&p.site===t.site&&p.month===month),accPass=isCity(t.site)?(t.accPassSnapshot!==undefined?Number(t.accPassSnapshot):!seen.has(passKey)?Number(pass?.amount||0):0):0;seen.add(passKey);return {...e,tripId:t.tripId,_id:t._id,site:t.site,srNo:index+1,date:new Date(t.periodFrom).toISOString().slice(0,10),vehicleNo:t.vehicleNumber,vehicleType:t.vehicleType,pickupLocation:t.pickupLocation,dropLocation:t.dropLocation,perTripHours:8,totalHours:Number(t.totalHours||0),gtInHours:Number(t.overtimeHours||0),tripCharges:Number(t.baseAmount||0),overtimeAmount:Number(t.overtimeAmount||0),nightDetentionAmount:Number(t.calculation?.nightDetentionAmount||0),overtimeRate:Number(t.overtimeRate||0),accPass,tollParking:parking,totalServiceCharges:Number(t.baseAmount||0)+parking,distanceBand:t.distanceBand};});
}
export function adhocSummary(rows){const sum=k=>Math.round(rows.reduce((n,r)=>n+Number(r[k]||0),0)*100)/100;return {tripAmount:sum("tripCharges"),otHours:rows.reduce((n,r)=>n+r.gtInHours,0),otAmount:sum("overtimeAmount"),accPass:sum("accPass"),parking:sum("tollParking"),night:sum("nightDetentionAmount"),total:Math.round((sum("tripCharges")+sum("overtimeAmount")+sum("tollParking")+sum("accPass")+sum("nightDetentionAmount"))*100)/100};}
export function adhocCell(row,key){return ["perTripHours","totalHours","gtInHours"].includes(key)?durationText(row[key]):row[key]??"";}

export function adhocColumns(site){return site==="Inbound"?cityColumns:site==="Outbound"?[...cityColumns.slice(0,3),cityColumns[4],["HUID NO","huNumber"],...cityColumns.slice(5).filter(([,key])=>key!=="mrbArrivalTime")]:kmColumns;}
